sudo: required
services:
  - docker
language: java
before_install:
  - docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD"
  - docker run -d --net=host mongo:latest
script:
  - docker build -t sdkman/sdkman-broker:1.7.0 .
  - docker run -d --env="RATPACK_MONGO__HOST=localhost" --net=host sdkman/sdkman-broker:1.7.0
  - "./gradlew check --stacktrace"
after_success:
  - docker push sdkman/sdkman-broker:1.7.0
cache:
  directories:
  - "$HOME/.gradle"
# blacklist
branches:
  except:
    - RELEASE
notifications:
  slack: sdkman:QdA1XVUuYDjlYL4Z7gm16OEc
