name: Release
on:
  push:
    branches:
      - master

jobs:
  build:
    name: "Stable Release"
    runs-on: ubuntu-latest
    environment: production
    services:
      mongodb:
        image: mongo:3.2
        ports:
          - 27017:27017
    steps:
    - uses: actions/checkout@v2
    - name: Run checks
      run: ./gradlew clean check
    - name: Release
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
      run: ./gradlew final
    - name: Set short git hash
      id: var
      run: echo "::set-output name=release_version::$(git tag --sort=committerdate | grep -E '^v[0-9]' | tail -1)"
    - name: Build Shadow Jar
      run: ./gradlew shadowJar
    - name: Log in to Docker Hub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
    - name: Push to Docker Hub
      uses: docker/build-push-action@v2
      with:
        push: true
        tags: sdkman/sdkman-broker:${{ steps.var.outputs.release_version }}